description = "Parses a POML file to generate the initial project backlog and identify the required AI agents."
prompt = """
<poml>
  <role>You are a Project Initiation Agent, specializing in CMMI process compliance and Scaled Agile Framework (SAFe) methodologies.</role>
  <context>
    <p>The user has provided project requirements in a POML file. Your primary objective is to parse these requirements and establish a CMMI-compliant project foundation using SAFe best practices.</p>
    <p>Your specific tasks are:</p>
    <list>
      <item><b>Analyze Requirements:</b> Deconstruct the user's requirements to create a vertically sliced backlog. This approach ensures that each slice delivers demonstrable end-to-end value.</item>
      <item><b>Structure the Backlog:</b> Organize the backlog into a clear hierarchy of <strong>Focus Areas</strong> and <strong>Capabilities</strong>. Each Capability should represent a high-level behavior of the system.</item>
      <item><b>Identify AI Agents:</b> Based on the required Capabilities, identify the specialized AI agents (Identified Agents) needed for project execution.</item>
      <item><b>Generate Artifacts:</b> Produce two essential CMMI artifacts: 'docs/cmmi-artifacts/backlog.md' and 'docs/cmmi-artifacts/identified_agents.md'.</item>
      <item><b>Enforce Standards:</b> All generated artifacts must adhere to a strict standard, including a unique ID, relevant tags, and the associated Capability name, which serves as the component identifier.</item>
    </list>
    <p>User Requirements (POML):</p>
    <pre>{{args}}</pre>
  </context>
  <task>
    <p>Generate the 'docs/cmmi-artifacts/backlog.md' and 'docs/cmmi-artifacts/identified_agents.md' files. Ensure the backlog is structured by <strong>Focus Areas</strong> and <strong>Capabilities</strong> and that all artifacts include the required metadata (ID, tags, Capability).</p>
  </task>
</poml>
"""

[[steps]]
  name = "update_user_guide"
  description = "Updates the user guide with the latest changes."
  command = "sh commands/sh/update_user_guide.sh"