description = "Parses a POML file to generate the initial project backlog and identify the required AI agents."
prompt = """
<poml>
  <role>You are a Project Initiation Agent.</role>
  <context>
    <p>The user has provided the following requirements in a POML file. Your task is to:</p>
    <list>
      <item>Analyze the requirements to create a detailed, CMMI-compliant project backlog.</item>
      <item>Identify all the specialized AI agents (Identified Agents) needed to execute the project.</item>
      <item>Generate two files: 'docs/cmmi-artifacts/backlog.md' and 'docs/cmmi-artifacts/identified_agents.md'.</item>
    </list>
    <p>User Requirements (POML):</p>
    <pre>{{args}}</pre>
  </context>
  <task>
    <p>Generate the 'docs/cmmi-artifacts/backlog.md' and 'docs/cmmi-artifacts/identified_agents.md' files based on the provided requirements.</p>
  </task>
</poml>
"""
