[command]
name = "with"
description = "Initiates a context-aware discussion session."
args = [
    { name = "identifier", description = "Bug ID, tag, or component name to search for.", type = "string" }
]

[script]
command = "python"
file = "with_command.py"

